apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: https://vault.mbtux.com:8200
    path: pki-int
    auth:
      kubernetes:
        mountPath: kubernetes/vault
        role: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-cert-manager-secret
  namespace: cert-manager
type: Opaque
stringData:
  token: CHANGEME_VAULT_TOKEN