apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-clusters
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: managed
  template:
    metadata:
      name: '{{metadata.name}}'
      labels:
        app: '{{metadata.name}}'
        env: managed
    spec:
      project: platform
      source:
        repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
        targetRevision: main
        path: management-infrastructure/bootstrap/apps
      destination:
        server: '{{server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true