apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared-mgmt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-mgmt
  namespace: cloudflared-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --config
        - /etc/cloudflared/config/config.yaml
        env:
        - name: CLOUDFLARE_TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: TUNNEL_TOKEN
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
      volumes:
      - name: config
        configMap:
          name: cloudflared-config