apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - redis.yaml
  - postgresql.yaml
  - authentik.yaml
  - ingressroute.yaml
  - certificate.yaml
