apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: outline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: outline-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: outline-secrets
      property: postgres-password
  - secretKey: redis-password
    remoteRef:
      key: outline-secrets
      property: redis-password
  - secretKey: smtp-username
    remoteRef:
      key: outline-secrets
      property: smtp-username
  - secretKey: smtp-password
    remoteRef:
      key: outline-secrets
      property: smtp-password
  - secretKey: smtp-from-address
    remoteRef:
      key: outline-secrets
      property: smtp-from-address
  - secretKey: slack-secret
    remoteRef:
      key: outline-secrets
      property: slack-secret
  - secretKey: oidc-client-secret
    remoteRef:
      key: outline-secrets
      property: oidc-client-secret
  - secretKey: SECRET_KEY
    remoteRef:
      key: outline-secrets
      property: SECRET_KEY
  - secretKey: UTILS_SECRET
    remoteRef:
      key: outline-secrets
      property: UTILS_SECRET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-oidc-client
  namespace: outline
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-oidc-client
    creationPolicy: Owner
  data:
  - secretKey: client-id
    remoteRef:
      key: outline-oidc
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: outline-oidc
      property: client-secret
