apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: outline
  namespace: outline
spec:
  secretName: tls-outline
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - outline.mbtux.com