apiVersion: v1
kind: Secret
metadata:
  name: traefik-authentik-oidc
  namespace: traefik
type: Opaque
stringData:
  # Session secret for OIDC plugin session encryption
  # Generate with: openssl rand -base64 32
  session-secret: "oTOY1HLvs7OHWz7FsB9urmnxff+NqmzESl1pANPl+ng="
  # OIDC client ID from Authentik
  client-id: "lq7UpiQKTUsI58m9QGeDYWVf1ZatctFi2u7mKwQO"
  # OIDC client secret from Authentik
  client-secret: "5HS1oKX10sWCyYhhhhl08e74umaePF71aSSi5dKok9ZMH4IJIv6BU1ETrpkMWFpuoSUFF83X7aG5ty63hEhBRdowr5iyio2XBa19UyB0oOIuZJxsqpNK8hy2j4P5vdcF"