ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

service:
  type: LoadBalancer

providers:
  kubernetesIngress:
    enabled: true

rbac:
  enabled: true

metrics:
  prometheus:
    enabled: true

ports:
  traefik:
    port: 9000
    expose:
      default: true

dashboard:
  enabled: true
  domain: traefik.mbtux.com