apiVersion: v1
kind: Secret
metadata:
  name: taiga-secrets
  namespace: taiga
type: Opaque
stringData:
  database-password: "taiga_db_pass"
  redis-password: ""
  rabbitmq-username: "taiga"
  rabbitmq-password: "taiga_rabbit_pass"
  smtp-host: "smtppro.zoho.eu"
  smtp-port: "465"
  smtp-tls-enabled: "true"
  smtp-username: "mritunjay.bhardwaj@mbtux.com"
  smtp-password: "7CsTsGcGbntE"
  email-sender: "Taiga <mritunjay.bhardwaj@mbtux.com>"