apiVersion: v1
kind: ConfigMap
metadata:
  name: wekan-config
  namespace: wekan
data:
  MONGO_URL: "mongodb://wekan-mongo:27017/wekan"
  ROOT_URL: "https://wekan.mbtux.com"
  PORT: "8080"
  NODE_ENV: "production"