apiVersion: v1
kind: Secret
metadata:
  name: wekan-secrets
  namespace: wekan
type: Opaque
stringData:
  mongo-password: "wekan_mongo_pass"
  admin-username: "admin"
  admin-password: "Inf0rm@tics@123"

  # Mail
  mail-from: "Wekan <mritunjay.bhardwaj@mbtux.com>"
  mail-url: "smtp://mritunjay.bhardwaj@mbtux.com:7CsTsGcGbntE@smtppro.zoho.eu:587"