apiVersion: v1
kind: Secret
metadata:
  name: wekan-secrets
  namespace: wekan
type: Opaque
stringData:
  mongo-password: "wekan_mongo_pass"
  admin-username: "admin"
  admin-password: "wekan_admin_pass"
  mail-from: "Wekan <mritunjay.bhardwaj@mbtux.com>"
  smtp-host: "smtppro.zoho.eu"
  smtp-port: "587"
  smtp-secure: "false"
  smtp-username: "mritunjay.bhardwaj@mbtux.com"
  smtp-password: "7CsTsGcGbntE"