apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wekan-ingressroute
  namespace: wekan
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`wekan.mbtux.com`)
    services:
    - name: wekan
      port: 80
    middlewares:
    - name: security-headers
    - name: compress
  tls:
    options:
      name: secure-default