apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared-data
data:
  config.yaml: |
    ingress:
      - hostname: outline.mbtux.com
        service: https://nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:443
        originRequest:
          caPool: /etc/cloudflared/certs/cloudflare-origin-ca.pem
      - hostname: authentik.mbtux.com
        service: https://nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:443
        originRequest:
          caPool: /etc/cloudflared/certs/cloudflare-origin-ca.pem
      - hostname: sure.mbtux.com
        service: https://nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:443
        originRequest:
          caPool: /etc/cloudflared/certs/cloudflare-origin-ca.pem
      - hostname: grafana.mbtux.com
        service: https://nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:443
        originRequest:
          caPool: /etc/cloudflared/certs/cloudflare-origin-ca.pem
      - service: http_status:404