apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared-data
data:
  config.yaml: |
    ingress:
      - hostname: outline.mbtux.com
        service: http://nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: authentik.mbtux.com
        service: http://nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: sure.mbtux.com
        service: http://nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - hostname: grafana.mbtux.com
        service: http://nginx-ingress-ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
      - service: http_status:404