apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-creds
  namespace: cloudflared-data
type: Opaque
stringData:
  credentials.json: |
    {
      "AccountTag": "5fc8bf9fd9d101833e550115fddab132",
      "TunnelID": "4139b149-9877-44f5-9cce-867db8680b1b",
      "TunnelSecret": "e7413c82-dc21-441b-8c12-442c85744807"
    }