apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflared-data
type: Opaque
stringData:
  TUNNEL_TOKEN: "eyJhIjoiNWZjOGJmOWZkOWQxMDE4MzNlNTUwMTE1ZmRkYWIxMzIiLCJ0IjoiYWUxZGQxMzQtNjg3NC00NDZkLWI2NjUtYjdhOWZhODFiMTRjIiwicyI6IlhJSmxXRzNxSjRpaGxxelh5MnhkTWI2OHVyUVpQcnROd0hZbmJzbHJ4dmtiREtqRWdGSUo4ekZQUVZEeEVQaXNjemQraHZLSEY2Z2RtUEM5ckdDc1pRPT0ifQ=="
