replicaCount: 1

image:
  registry: ghcr.io
  repository: headlamp-k8s/headlamp
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: headlamp-admin

config:
  inCluster: true
  enableHelm: true

ingress:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi