apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-headers
  namespace: monitoring
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
    accessControlMaxAge: 100
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
      - HEAD
    accessControlAllowOriginList:
      - "*"
    accessControlAllowHeaders:
      - Content-Type
      - Authorization
      - Origin
      - Accept
    addVaryHeader: true

    customFrameOptionsValue: SAMEORIGIN
    sslRedirect: true
