apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: traefik-oidc-auth
    namespace: traefik
spec:
    plugin:
        traefik-oidc-auth:
            Provider:
                ClientId: <YourClientId>
                ClientSecret: <YourClientSecret>
                Url: https://authentik.mbtux.com/application/o/authorize/
            Scopes:
                - openid
                - profile
                - email
