defaultNamespace: vault
kustomize:
  dir: ./manifests

helm:
  releaseName: vault
  repo: https://helm.releases.hashicorp.com
  chart: vault
  version: 0.27.0
  valuesFiles:
    - values.yaml

dependsOn: []
