apiVersion: v1
kind: Secret
metadata:
  name: outline-secrets
  namespace: outline
type: Opaque
stringData:
  postgres-password: "REPLACE_WITH_STRONG_PASSWORD"
  redis-password: ""
  smtp-username: "mritunjay.bhardwaj@mbtux.com"
  smtp-password: "7CsTsGcGbntE"
  smtp-from-address: "Outline <mritunjay.bhardwaj@mbtux.com>"
  slack-secret: ""
  oidc-client-secret: "5OB4WjmXTbVxJyNAa6NeqO2P4HEyXncm5D6jeTwKdII3Qjd5F3ygu7twXY0p"