apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: outline

resources:
  - namespace.yaml

helmCharts:
  - name: outline
    repo: oci://ghcr.io/community-charts/charts/outline
    releaseName: outline
    namespace: outline
    valuesFile: values.yaml