apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: outline

resources:
  - namespace.yaml

helmCharts:
  - name: outline
    repo: https://community-charts.github.io/charts
    releaseName: outline
    namespace: outline
    valuesFile: values.yaml