apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-root
  namespace: argocd
  labels:
    app.kubernetes.io/name: mgmt-root
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.tier: management
    app.kubernetes.io/component: app-of-apps
spec:
  project: default

  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: gitops

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    # Manual sync - only sync on explicit GitHub push
    automated: {}
