apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - ../data-infrastructure/project.yaml
  - ../data-infrastructure/cert-manager-helm.yaml
  - ../data-infrastructure/cloudflared-kustomize.yaml
  - ../data-infrastructure/monitoring-kustomize.yaml
  - ../data-infrastructure/traefik-helm.yaml
  - ../data-infrastructure/traefik-infra.yaml