apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - ../data-infrastructure/project.yaml
  - ../data-infrastructure/prod-infra-cert-manager-kustomize.yaml
  - ../data-infrastructure/prod-infra-traefik-infra.yaml
  - ../data-infrastructure/prod-infra-monitoring-kustomize.yaml
  - ../data-infrastructure/prod-infra-traefik-helm.yaml
  - ../data-infrastructure/prod-infra-authentik-kustomize.yaml
  - ../data-infrastructure/prod-apps-sure.yaml
  - ../data-infrastructure/prod-apps-outline.yaml
