apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-prod-cloudflared
  namespace: argocd
  labels:
    app.kubernetes.io/name: data-prod-cloudflared
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.scope: data
    platform.cluster: data-prod
    app.kubernetes.io/component: infrastructure
spec:
  project: data-prod-infrastructure

  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: production-infrastructure/cloudflared-data/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
