apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-infra-external-secrets-store
  namespace: argocd
  labels:
    app.kubernetes.io/name: prod-infra-external-secrets-store
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.scope: data
    platform.cluster: data-prod
    app.kubernetes.io/component: infrastructure
spec:
  project: data-prod-infrastructure

  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: clusters/data-prod/external-secrets-store/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: eso-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
