apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-infra-traefik-infra
  namespace: argocd
  labels:
    app.kubernetes.io/name: prod-infra-traefik-infra
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.scope: data
    platform.cluster: data-prod
    app.kubernetes.io/component: infrastructure
spec:
  project: data-prod-infrastructure
  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: clusters/data-prod/traefik
  destination:
    server: https://192.168.0.211:6443
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # Manual sync - only sync on explicit GitHub push
    automated: null
