apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-infra-external-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: prod-infra-external-secrets
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.scope: data
    platform.cluster: data-prod
    app.kubernetes.io/component: infrastructure
spec:
  project: data-prod-infrastructure

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.4.1
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        nodeSelector:
          kubernetes.io/os: linux

  destination:
    server: https://192.168.0.211:6443
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
