apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-infra-monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/name: prod-infra-monitoring
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.scope: data
    platform.cluster: data-prod
    app.kubernetes.io/component: infrastructure
spec:
  project: data-prod-infrastructure

  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: production-infrastructure/monitoring-data/manifests

  destination:
    server: https://192.168.0.211:6443
    namespace: monitoring

  syncPolicy:
    # Manual sync - only sync on explicit GitHub push
    automated: {}
