apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: data-prod-workloads
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.scope: data
    platform.cluster: data-prod
spec:
  description: Production data workloads (application services)

  sourceRepos:
    - https://github.com/mrbhardw-dev/mbtux-kubernetes.git

   destinations:
     - namespace: authentik
       server: https://api.data-prod-cluster.mbtux.com:6443
     - namespace: outline
       server: https://api.data-prod-cluster.mbtux.com:6443
     - namespace: sure
       server: https://api.data-prod-cluster.mbtux.com:6443
     - namespace: coder
       server: https://api.data-prod-cluster.mbtux.com:6443

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
