apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  selector:
    app: node-exporter
  type: NodePort
  ports:
    - name: cadvisor
      port: 10250
      targetPort: 10250
      nodePort: 30250