prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    externalLabels:
      cluster: mgmt
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: traefik-traefik-headers@kubernetescrd
      hosts:
        - prometheus.mgmt.mbtux.com
      paths:
        - /
      pathType: Prefix

grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: true

coreDns:
  enabled: false

kubeApiServer:
  enabled: true

kubelet:
  enabled: true

kubeControllerManager:
  enabled: true

kubeScheduler:
  enabled: true

kubeEtcd:
  enabled: true