apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud-aio

resources:
  - namespace.yaml

helmCharts:
  - name: nextcloud-aio
    repo: https://nextcloud.github.io/all-in-one/
    releaseName: nextcloud-aio
    namespace: nextcloud-aio
    valuesFile: values.yaml