NC_DOMAIN: nextcloud.mbtux.com
NEXTCLOUD_PASSWORD: "Inf0rm@tics@123"
DATABASE_PASSWORD: "Inf0rm@tics@123"
REDIS_PASSWORD: "Inf0rm@tics@123"
FULLTEXTSEARCH_PASSWORD: "Inf0rm@tics@123"
IMAGINARY_SECRET: "Inf0rm@tics@123"
ONLYOFFICE_SECRET: "Inf0rm@tics@123"
RECORDING_SECRET: "Inf0rm@tics@123"
SIGNALING_SECRET: "Inf0rm@tics@123"
TALK_INTERNAL_SECRET: "Inf0rm@tics@123"
TURN_SECRET: "Inf0rm@tics@123"
WHITEBOARD_SECRET: "Inf0rm@tics@123"
TIMEZONE: "Europe/Berlin"

CLAMAV_ENABLED: "no"
COLLABORA_ENABLED: "no"
FULLTEXTSEARCH_ENABLED: "no"
IMAGINARY_ENABLED: "no"
ONLYOFFICE_ENABLED: "no"
TALK_ENABLED: "no"
TALK_RECORDING_ENABLED: "no"
WHITEBOARD_ENABLED: "no"
NEXTCLOUD_ADDITIONAL_APKS: imagemagick
NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS: imagick
NEXTCLOUD_MEMORY_LIMIT: 512M
NEXTCLOUD_UPLOAD_LIMIT: 16G
NEXTCLOUD_MAX_TIME: 3600
APACHE_PORT: 443

APACHE_STORAGE_SIZE: 1Gi
NEXTCLOUD_STORAGE_SIZE: 5Gi
NEXTCLOUD_DATA_STORAGE_SIZE: 10Gi
DATABASE_STORAGE_SIZE: 5Gi
REDIS_STORAGE_SIZE: 1Gi