apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  DB_HOST: "immich-postgres"
  DB_PORT: "5432"
  DB_URL: "postgres://immich_user:immich_db_pass@immich-postgres:5432/immich"
  DB_DATENAME: "immich"
  REDIS_HOST: "immich-redis"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://immich-redis:6379/0"
  UPLOAD_LOCATION: "/photos"
  PUBLIC_LOGIN_PAGE_MESSAGE: "Welcome to Immich"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
  TYPESENSE_ENABLED: "false"