apiVersion: v1
kind: Secret
metadata:
  name: immich-secrets
  namespace: immich
type: Opaque
stringData:
  postgres-password: "immich_db_pass"
  postgres-user: "immich_user"
  secret-key: "immich-secret-key-change-in-production"