apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: data-cluster
  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes
    targetRevision: main
    path: apps/immich
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true