apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring
  labels:
    fleet.cattle.io/managed: "true"
type: Opaque
stringData:
  grafana-password: "Inf0rm@tics@123"
  prometheus-retention: "15d"
  authentik-client-secret: "UjMBeLDPD8NYYHDE9tDtTxv3yQsKJ3lTqiY2takuQL1gqprfhhLyZIIlHoOz60TJDipBvx5ySijrhIH6hfSZIo15hXEVaLs7Ymr4Q76swq0nystjLzLZMPOKGD5jxujs"
