apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    
    datasources:
      - name: Prometheus (data-cluster)
        type: prometheus
        access: proxy
        url: https://prometheus.data.mbtux.com
        isDefault: true
        editable: true
        jsonData:
          httpMethod: POST
          timeInterval: 30s
          tlsSkipVerify: true
      - name: Prometheus (mgmt-cluster)
        type: prometheus
        access: proxy
        url: https://prometheus.mgmt.mbtux.com
        editable: true
        jsonData:
          httpMethod: POST
          timeInterval: 30s
          tlsSkipVerify: true

      - name: Prometheus (mgmt-cluster)
        type: prometheus
        access: proxy
        url: http://prometheus.mgmt-cluster-prometheus.monitoring.svc.cluster.local:9090
        editable: true
        jsonData:
          httpMethod: POST
          timeInterval: 30s
