apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-aio
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/nextcloud/all-in-one
      targetRevision: main
      path: nextcloud-aio-helm-chart/versions/latest
      helm:
        valueFiles:
          - $values/nextcloud/values.yaml
    - repoURL: https://github.com/mrbhardw-dev/ArgoCD
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true