apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-aio-mastercontainer
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi