apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plane

resources:
  - 00-namespace.yaml

helmCharts:
- name: plane-ce
  version: latest
  repo: https://makeplane.github.io/helm-charts
  releaseName: plane
  namespace: plane
  valuesFile: values.yaml
  includeCRDs: true