defaultNamespace: argocd
kustomize:
  dir: ./manifests
helm:
  releaseName: argocd
  chart: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: "9.5.2"
  valuesFiles:
    - values.yaml
  force: true
target:
  clusterSelector:
    matchLabels:
      cluster: data
