apiVersion: v1
kind: Service
metadata:
  name: {{ include "codecombat.fullname" . }}
  namespace: {{ include "codecombat.namespace" . }}
  labels:
    {{- include "codecombat.appLabels" . | nindent 4 }}
spec:
  type: {{ .Values.codecombat.service.type }}
  ports:
    - port: {{ .Values.codecombat.service.port }}
      targetPort: {{ .Values.codecombat.port }}
      name: http
  selector:
    {{- include "codecombat.appSelectorLabels" . | nindent 4 }}
