apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "codecombat.fullname" . }}-config
  namespace: {{ include "codecombat.namespace" . }}
  labels:
    {{- include "codecombat.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.codecombat.port | quote }}
  COCO_ENV: {{ .Values.config.cocoEnv | quote }}
  COCO_ANALYTICS: {{ .Values.config.cocoAnalytics | quote }}
  COCO_SSL_HIERARCHY: {{ .Values.config.cocoSslHierarchy | quote }}
  COCO_DISABLE_THANG_SAVING: {{ .Values.config.cocoDisableThangSaving | quote }}
  COCO_PROXY: {{ .Values.config.cocoProxy | quote }}
  {{- range $key, $value := .Values.codecombat.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
