{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ include "codecombat.namespace" . }}
  labels:
    {{- include "codecombat.mongodbLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
      name: mongodb
  selector:
    {{- include "codecombat.mongodbSelectorLabels" . | nindent 4 }}
{{- end }}
