apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codecombat.fullname" . }}-secrets
  namespace: {{ include "codecombat.namespace" . }}
  labels:
    {{- include "codecombat.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.mongoUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.mongoPassword | quote }}
  COCO_MONGO_URL: {{ include "codecombat.mongodbUrl" . | quote }}
  {{- if .Values.secrets.smtpPassword }}
  COCO_SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  {{- end }}
