apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: identity
    cluster: data
spec:
  project: data-cluster
  source:
    repoURL: https://github.com/goauthentik/helm
    chart: authentik
    targetRevision: 2025.12.2
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: authentik.secret_key
          value: e0a66085992a094ef36a2a7dc73f149d66d5bd4f71fe687414279f4a34b4e4b7
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m