apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: identity
    cluster: data
spec:
  project: data-cluster
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: 2025.12.2
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m