global:
  fullnameOverride: authentik
  domain: authentik.mbtux.com

authentik:
  secret_key: "e0a66085992a094ef36a2a7dc73f149d66d5bd4f71fe687414279f4a34b4e4b7"
  bootstrap_insecure: true
  postgresql:
    host: sure-postgres.sure.svc.cluster.local
    port: 5432
    name: sure_development
    user: sure_user
    password: sure_db_pass
  redis:
    host: sure-redis.sure.svc.cluster.local
    port: 6379

server:
  replicas: 1

worker:
  replicas: 1

postgresql:
  enabled: false

persistence:
  enabled: true
  size: 10Gi