apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mgmt-platform
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - https://argoproj.github.io/argo-helm
    - https://github.com/mrbhardw-dev/mbtux-kubernetes.git
