apiVersion: v1
kind: Secret
metadata:
  name: sure-secrets
  namespace: sure
type: Opaque
stringData:
  SECRET_KEY_BASE: "a7523c3d0ae56415046ad8abae168d71074a79534a7062258f8d1d51ac2f76d3c3bc86d86b6b0b307df30d9a6a90a2066a3fa9e67c5e6f374dbd7dd4e0778e13"
  secret-key-base: "56f19bdf7f6a9e94a3fc661de4ece79788e783df7d27aee763a9d4d8918a3f3847c4273281a15867d4095cac5a0c6038c8d2907c9dab9842b3abfdf8e9ca81cc"

  postgres-user: "sure_user"
  postgres-password: "fZwzeqAJTLwjyN+fpWTSvRauphyf49NYxmqP3MKnsE4="

  smtp-host: "smtppro.zoho.eu"
  smtp-port: "587"
  smtp-tls-enabled: "true"
  smtp-username: "mritunjay.bhardwaj@mbtux.com"
  smtp-password: "7CsTsGcGbntE"

  email-sender: "Sure <mritunjay.bhardwaj@mbtux.com>"

  OIDC_CLIENT_SECRET: "m0PHV2PpWtbR1WYuTOC0QTyGwxDhZ8H1D7MXmVxQaxFoUztSWr9iU1dOcNfuJqCokKra0D6VwYJ4GpZMrPz4Z36d1wmdEtqtkKFMsFbm3ty1vdeaLameIycHSApBZKOu"
