apiVersion: v1
kind: Secret
metadata:
  name: authentik-oidc-client
  namespace: sure
type: Opaque
data:
  client-id: N1NubTlidjJacG9VOWRhcHhINkRCS1ljeVc1Q2ticHVGaVlnM0Z5Nw==
  client-secret: bTBQSFYyUHBXdGJSMVdZdVRPQzBRVHlHd3hEaFo4SDFEN01YbVZ4UWF4Rm9VenRTV3I5aVUxZE9jTmZ1SnFDb2tLcmEwRDZWd1lKNEdwWk1yUHo0WjM2ZDF3bWRFdHF0a0tGTXNGYm0zdHkxdmRlYUxhbWVJeWNIU0FwQlpLT3U=
