apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sure-ingress
  namespace: sure
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: sure.mbtux.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sure
            port:
              number: 80