namespace: cattle-system

hostname: rancher.mbtux.com

replicas: 2

image:
  tag: v2.10.2

bootstrapPassword: admin

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

ingress:
  enabled: true
  className: traefik
  hostname: rancher.mbtux.com
  tls:
    source: letsencrypt

letsencrypt:
  enabled: true
  email: mritunjay.bhardwaj@mbtux.com

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 20Gi
  storageClass: longhorn

bootstrap:
  enabled: true