apiVersion: v1
kind: Secret
metadata:
  name: authentik-outpost-token
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: outpost
type: Opaque
stringData:
  token: iNUZ2O63l1x5Sn8ntW4J4Kgyf4IxPPu8tFbqEGtmThzVME45aglHHn7vKwFM
