apiVersion: v1
kind: Secret
metadata:
  name: outline-secrets
  namespace: outline
type: Opaque
stringData:
  postgres-password: "JznZcRdWEHMtYfvNqSY9h+bIL3F+OTE0LVMJpqXRrbY="
  redis-password: ""
  smtp-username: "mritunjay.bhardwaj@mbtux.com"
  smtp-password: "SMN/z7PB0sUac44VQA1UuxNGOC9PZE9of7d+mKqwaFM="
  smtp-from-address: "Outline <mritunjay.bhardwaj@mbtux.com>"
  slack-secret: ""
  oidc-client-secret: "ObXp9gcl67T81fcbWuNq6ZJA13UzsMVWaEZhA4D4H0Q="