apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: outline

resources:
  - 00-namespace.yaml
  - 01-config.yaml
  - 02-secret.yaml
  - 03-auth.yaml
  - oidc-secret.yaml
  - 10-postgres.yaml
  - 11-redis.yaml
  - certificate.yaml
  - 20-outline.yaml
  - ingressroute.yaml