apiVersion: v1
kind: Secret
metadata:
  name: authentik-oidc-client
  namespace: outline
type: Opaque
data:
  client-id: UG9PQ2UwQnFUcjZWYUJIb1dWUmN3TGVzQURXZWFZSDdnaDBKdUJkcA==
  client-secret: dEJxcW9PaW1RRjc1dTFQcFJYTENpYWNScWhsZWo0Ym5EUWpxaTU2emZLRU5FR0l3SW1pMVgyMFhjWXR1T2dCcnhKWmpaZUdxNHpFQjhoVGxhWXZDY25qb3B6bFpGVzFzY2w2RVM5QklmQWhzUklBU3pzWjkzV3lnNXZ4ZmRocks=
