apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: monitoring
type: Opaque
stringData:
  grafana-password: "Inf0rm@tics@123"
  prometheus-retention: "15d"
  authentik-client-secret: "o2BPVFFHistGCr4RPZRJa5FDe1/yQvCiwJytB2JD2nc="