apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mbtux-kubernetes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Main project for all infrastructure and applications in the mbtux-kubernetes cluster
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      policies:
        - p, role:admin, applications, get, mbtux-kubernetes/*, allow
        - p, role:admin, applications, list, mbtux-kubernetes/*, allow
        - p, role:admin, applications, create, mbtux-kubernetes/*, allow
        - p, role:admin, applications, update, mbtux-kubernetes/*, allow
        - p, role:admin, applications, delete, mbtux-kubernetes/*, allow
        - p, role:admin, projects, get, mbtux-kubernetes, allow
      groups:
        - argocd-admins
