apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - cert-manager-kustomize.yaml
  - cloudflared-kustomize.yaml
  - monitoring-kustomize.yaml
  - traefik-helm.yaml
  - traefik-infra.yaml
  - traefik-management-helm.yaml
  - traefik-mgmt.mbtux.com.yaml
