apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-platform-infra
  namespace: argocd
  labels:
    app.kubernetes.io/name: mgmt-platform-infra
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.tier: management
    app.kubernetes.io/component: infrastructure
spec:
  project: mgmt-platform

  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: management-infrastructure/traefik

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
