apiVersion: v1
kind: Secret
metadata:
  name: sure-secrets
  namespace: sure
type: Opaque
stringData:
  secret-key-base: "56f19bdf7f6a9e94a3fc661de4ece79788e783df7d27aee763a9d4d8918a3f3847c4273281a15867d4095cac5a0c6038c8d2907c9dab9842b3abfdf8e9ca81cc"

  postgres-user: "sure_user"
  postgres-password: "sure_db_pass"

  smtp-host: "smtppro.zoho.eu"
  smtp-port: "587"
  smtp-tls-enabled: "true"
  smtp-username: "mritunjay.bhardwaj@mbtux.com"
  smtp-password: "7CsTsGcGbntE"

  email-sender: "Sure <mritunjay.bhardwaj@mbtux.com>"

  smtp-settings: >
    {
      "address":"smtppro.zoho.eu",
      "port":"587",
      "user_name":"mritunjay.bhardwaj@mbtux.com",
      "password":"7CsTsGcGbntE",
      "authentication":"plain",
      "enable_starttls_auto":true
    }

  OIDC_CLIENT_SECRET: "5OB4WjmXTbVxJyNAa6NeqO2P4HEyXncm5D6jeTwKdII3Qjd5F3ygu7twXY0p"