apiVersion: v1
kind: Secret
metadata:
  name: sure-secrets
  namespace: sure
type: Opaque
stringData:
  secret-key-base: "f2effcf4a80f005aca64c4ef1a988b3a960d0fb00146387f4e5484c25ee5c2c973e33096c72def36a16a494285e3e2f3002958d7dd449ee5d6e2d83145b7dcfc"
  RAILS_MASTER_KEY: "f2effcf4a80f005aca64c4ef1a988b3a960d0fb00146387f4e5484c25ee5c2c973e33096c72def36a16a494285e3e2f3002958d7dd449ee5d6e2d83145b7dcfc"

  postgres-user: "sure_user"
  postgres-password: "sure_db_pass"

  smtp-host: "smtppro.zoho.eu"
  smtp-port: "587"
  smtp-tls-enabled: "true"
  smtp-username: "mritunjay.bhardwaj@mbtux.com"
  smtp-password: "7CsTsGcGbntE"

  email-sender: "Sure <mritunjay.bhardwaj@mbtux.com>"

  smtp-settings: >
    {
      "address":"smtppro.zoho.eu",
      "port":"587",
      "user_name":"mritunjay.bhardwaj@mbtux.com",
      "password":"7CsTsGcGbntE",
      "authentication":"plain",
      "enable_starttls_auto":true
    }

  OIDC_CLIENT_SECRET: "5OB4WjmXTbVxJyNAa6NeqO2P4HEyXncm5D6jeTwKdII3Qjd5F3ygu7twXY0p"