apiVersion: v1
kind: Secret
metadata:
  name: sure-secrets
  namespace: sure
type: Opaque
stringData:
  secret-key-base: "77e752ac0a0e510f1c4429617212a0081737b26d2b2cbe6d47d0b3417d35f9b8"

  postgres-user: "sure_user"
  postgres-password: "sure_db_pass"

  smtp-host: "smtppro.zoho.eu"
  smtp-port: "587"
  smtp-tls-enabled: "true"
  smtp-username: "mritunjay.bhardwaj@mbtux.com"
  smtp-password: "7CsTsGcGbntE"

  email-sender: "Sure <mritunjay.bhardwaj@mbtux.com>"

  smtp-settings: >
    {
      "address":"smtppro.zoho.eu",
      "port":"587",
      "user_name":"mritunjay.bhardwaj@mbtux.com",
      "password":"7CsTsGcGbntE",
      "authentication":"plain",
      "enable_starttls_auto":true
    }

  OIDC_CLIENT_SECRET: "5OB4WjmXTbVxJyNAa6NeqO2P4HEyXncm5D6jeTwKdII3Qjd5F3ygu7twXY0p"