apiVersion: v1
kind: ConfigMap
metadata:
  name: sure-auth
  namespace: sure
data:
  AUTH_ENABLED: "true"

  OIDC_PROVIDER: "authentik"
  AUTH_JIT_MODE: "create_and_link"
  AUTH_LOCAL_ENABLED: "false"
  OIDC_ISSUER: "https://authentik.mbtux.com/application/o/sure-finance/"
  OIDC_ISSUER_URL: "https://authentik.mbtux.com/application/o/sure-finance/"
  
  OIDC_CLIENT_ID: "sure-finance"
  OIDC_REDIRECT_URI: "https://sure.mbtux.com/auth/openid_connect/callback"
  OIDC_SCOPES: "openid profile email"