apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/part-of: infrastructure
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/part-of: infrastructure
    cluster: mgmt
spec:
  project: mgmt-cluster
  source:
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.10.3
    chart: rancher
    helm:
      valueFiles:
        - values.yaml
      values: |
        hostname: rancher.mbtux.com
        replicas: 1
        bootstrapPassword: "admin"
        tls: external
        ingress:
          enabled: true
          ingressClassName: nginx
          extraAnnotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
        service:
          type: ClusterIP
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
        noAntiAffinity: "true"
        auditLevel: 0
        debug: false
  destination:
    server: https://192.168.0.201:6443
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
