apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/part-of: infrastructure
    cluster: mgmt
  annotations:
    description: "Rancher management server namespace"
