apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-token
    creationPolicy: Owner
  data:
  - secretKey: TUNNEL_TOKEN
    remoteRef:
      key: cloudflared-token
      property: TUNNEL_TOKEN
