apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - certificate.yaml
  - postgresql.yaml
  - redis.yaml
  - deployment.yaml
  - ingressroute.yaml
  - ../outpost/deployment.yaml
  - ../outpost/secret.yaml
