apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: authentik-worker-pdb
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
