apiVersion: v1
kind: Secret
metadata:
  name: proxmox-csi-data-secret
  namespace: kube-system
type: Opaque
stringData:
  PROXMOX_URL: "https://proxmox.mbtux.com:8006/api2/json"
  PROXMOX_USER: "kubernetes@pve!csi"
  PROXMOX_TOKEN: "8054dc11-f081-4ca1-a21c-a22b29020fe7"
  PROXMOX_INSECURE: "true"