apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-zfs
provisioner: csi.proxmox.sinextra.dev
parameters:
  storage: local   # MUST match Proxmox storage name
  fstype: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true