existingConfigSecret: proxmox-csi-data-secret
existingConfigSecretKey: config.yaml

controller:
  enabled: true

node:
  enabled: true

storageClass: []  # we manage it ourselves

rbac:
  create: true

serviceAccount:
  create: true
