config:
  existingSecret: proxmox-csi-data-secret

controller:
  enabled: true

node:
  enabled: true

storageClass: []  # we manage it ourselves

rbac:
  create: true

serviceAccount:
  create: true
