apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-mgmt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: management/cloudflared-mgmt/manifests
    directory:
      recurse: true
  destination:
    name: mgmt-cluster
    namespace: cloudflared-mgmt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
