apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-mgmt-headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: headlamp-system
    server: https://192.168.0.201:6443
  project: mbtux-kubernetes
  source:
    path: management/headlamp-mgmt/manifests
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true