apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: apps/outline/manifests
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: outline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
