apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-infra
  namespace: argocd
  labels:
    app: nginx-ingress
    env: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: infrastructure/nginx-ingress/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true