defaultNamespace: ingress-nginx
kustomize:
  dir: ./manifests
helm:
  releaseName: nginx-ingress
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.10.0
  takeOwnership: true
  valuesFile: values.yaml