apiVersion: v1
kind: Secret
metadata:
  name: argocd-oidc-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-oidc-secret
    app.kubernetes.io/part-of: mbtux-platform
type: Opaque
stringData:
  # OIDC client ID from Authentik ArgoCD provider
  client-id: "lq7UpiQKTUsI58m9QGeDYWVf1ZatctFi2u7mKwQO"
  # OIDC client secret from Authentik ArgoCD provider
  client-secret: "5HS1oKX10sWCyYhhhhl08e74umaePF71aSSi5dKok9ZMH4IJIv6BU1ETrpkMWFpuoSUFF83X7aG5ty63hEhBRdowr5iyio2XBa19UyB0oOIuZJxsqpNK8hy2j4P5vdcF"