global:
  logging:
    format: json
    level: info

image:
  tag: v3.0.0

namespace: argocd

server:
  replicas: 2

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi

  service:
    type: ClusterIP

  extraArgs:
    - --insecure=true

  ingress:
    enabled: false   # ✅ IMPORTANT

controller:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi

repoServer:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi

applicationSet:
  enabled: true
  replicas: 2

dex:
  enabled: true
  replicas: 2

notifications:
  enabled: true

redis:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

ha:
  enabled: true
  redisProxyReplicas: 2
  redisHa:
    enabled: true
    haproxy:
      enabled: true