global:
  logging:
    format: json
    level: info

image:
  tag: v3.0.0

namespace: argocd

server:
  replicas: 2

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi

  service:
    type: ClusterIP

  extraArgs:
    - --insecure=true

  ingress:
    enabled: false   # ✅ IMPORTANT

controller:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi

repoServer:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi
  env:
    - name: HELM_CACHE_HOME
      value: /tmp/helm/cache
    - name: HELM_CONFIG_HOME
      value: /tmp/helm/config
    - name: HELM_DATA_HOME
      value: /tmp/helm/data
    - name: HTTP_PROXY
      value: ""
    - name: HTTPS_PROXY
      value: ""
    - name: NO_PROXY
      value: "localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  dnsPolicy: ClusterFirst
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1

applicationSet:
  enabled: true
  replicas: 2

dex:
  enabled: true
  replicas: 2

notifications:
  enabled: true

redis:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

ha:
  enabled: true
  redisProxyReplicas: 2
  redisHa:
    enabled: true
    haproxy:
      enabled: true