apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - root/application.yaml
  - argocd/argocd-mgmt-infra.yaml
  - argocd/argocd-mgmt-helm.yaml
  - argocd/project.yaml
  - infrastructure/cert-manager-helm.yaml
  - infrastructure/traefik-helm.yaml
  - infrastructure/project.yaml