apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-mgmt-infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: root-mgmt-infrastructure
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.tier: management
    app.kubernetes.io/component: root
spec:
  project: default

  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: gitops/mgmt-infrastructure

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: null
