apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-data-prod-infrastructure
  namespace: argocd
  labels:
    app.kubernetes.io/name: root-data-prod-infrastructure
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/managed-by: argocd
    platform.scope: data
    platform.cluster: data-prod
    app.kubernetes.io/component: root
spec:
  project: data-prod-infrastructure

  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: gitops/data-infrastructure
    directory:
      include: '*-infra*.yaml'

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # Manual sync - only sync on explicit GitHub push
    automated: null
