apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: identity

resources:
  - namespace.yaml
  - masterkey-secret.yaml
  - placeholder-secrets.yaml
  - ingress.yaml

helmCharts:
  - name: zitadel
    releaseName: zitadel
    namespace: identity
    valuesFile: values.yaml
    includeCRDs: false
    chart: ./charts/zitadel
