apiVersion: v1
kind: Secret
metadata:
  name: zitadel-masterkey
  namespace: identity
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  masterkey: VXlTTGJ1Wm9WeEFnSk4yRmp2c1J2RWJzYjVCeVErWWg=
