apiVersion: v1
kind: Secret
metadata:
  name: iam-admin
  namespace: identity
  labels:
    app.kubernetes.io/managed-by: Zitadel
    app.kubernetes.io/name: zitadel
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  iam-admin.json: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: iam-admin-pat
  namespace: identity
  labels:
    app.kubernetes.io/managed-by: Zitadel
    app.kubernetes.io/name: zitadel
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  pat: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: login-client
  namespace: identity
  labels:
    app.kubernetes.io/managed-by: Zitadel
    app.kubernetes.io/name: zitadel
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  pat: ""
