postgresql:
  enabled: true
  auth:
    database: zitadel
    username: zitadel
    password: zitadel
    postgresPassword: zitadel
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: local-path

zitadel:
  masterkeySecretName: zitadel-masterkey
  configmapConfig:
    ExternalDomain: auth.mbtux.com
    ExternalSecure: true
    ExternalPort: 443
    TLS:
      Enabled: false
    FirstInstance:
      Org:
        Human:
          UserName: admin
          Email: admin@mbtux.com
          Password: "Admin@2026!"
          PasswordChangeRequired: true
        LoginClient:
          Machine:
            Username: login-client
            Name: Login Client
          Pat:
            ExpirationDate: "2029-12-31T00:00:00Z"

replicaCount: 1

login:
  enabled: false

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi