postgresql:
  enabled: true
  commonAnnotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  auth:
    database: zitadel
    username: zitadel
    password: zitadel
    postgresPassword: zitadel
  primary:
    persistence:
      enabled: true
      size: 10Gi

zitadel:
  masterkeySecretName: zitadel-masterkey

  configmapConfig:
    ExternalDomain: auth.mbtux.com
    ExternalSecure: true
    ExternalPort: 443

    TLS:
      Enabled: false

    FirstInstance:
      Org:
        Human:
          UserName: admin
          Email: admin@mbtux.com
          Password: "Admin@2026!"
          PasswordChangeRequired: true

    SMTP:
      Host: smtppro.zoho.eu
      Port: 587
      TLS: true
      From: "mritunjay.bhardwaj@mbtux.com"
      FromName: "ZITADEL Auth"

  secretConfig:
    SMTP:
      User: "mritunjay.bhardwaj@mbtux.com"
      Password: "7CsTsGcGbntE"

  debug:
    enabled: true

replicaCount: 1

ingress:
  enabled: true
  controller: nginx
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: auth.mbtux.com
      paths:
        - path: /
          pathType: Prefix

login:
  enabled: true
  replicaCount: 1

  ingress:
    enabled: true
    controller: nginx
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
      - host: auth.mbtux.com
        paths:
          - path: /ui/v2/login
            pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
