apiVersion: v1
kind: Secret
metadata:
  name: cluster-prod-data
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: data-prod
  server: https://192.168.0.211:6443
  config: |
    {
      "bearerToken": "",
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      }
    }
