apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared-data
data:
  config.yaml: |
    tunnel: ae1dd134-6874-446d-b665-b7a9fa81b14c
# INGRESS IS MANAGED BY THE CLOUDFLARE DASHBOARD