apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-data
  namespace: argocd
  labels:
    app: cloudflared
    env: infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: infrastructure/cloudflared-data/manifests
  destination:
    server: https://192.168.0.211:6443
    namespace: cloudflared-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true