# Management cluster credentials for Argo CD
apiVersion: v1
kind: Secret
metadata:
  name: cluster-mgmt
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
    argocd.argoproj.io/secret-type: cluster
    cluster: mgmt
type: Opaque
stringData:
  name: mgmt
  server: "https://192.168.0.201:6443"
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjktM0oxTEFGUFhfMGJBaS1ISDgwT2pXYmFhMnJqZWlUUEg1Y3lOR1NETGcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiYXJnb2NkLW1hbmFnZXItdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiYXJnb2NkLW1hbmFnZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI5NzlmNzc5Yy05NGYwLTQwNGYtODY4My0wMjAzYjM1NDUzOGEiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6YXJnb2NkOmFyZ29jZC1tYW5hZ2VyIn0.pO4CPXrZd3WnX8ubnUzNEWo0qU5jV9lkWWhUnR45HzchMBU3090jMGAf0Li1crQrLiVKyZtjkvgPAuZy_gwS-x8KscL-Dqz0Zlnuk6f1s0Zsxy7RLS8tYiLQ-eqcvb8RyvxF1YChVLloewoArYMQnvPDRtrQWSnt8Z95SbLW__kWHbXwyF-8yG_0D-lPV7_Hsl5aY8SEvTj7oPl7g7_1PKfuhzJkcJ89skWDLbad_L8S1nZnyiX3FEERt0iJcO5M0vwzpw3Jrf-uGsWk-uWuuW4Sc3qU85GtNEQZOIGyPzccMc7Wx4_NbADpOWfbQn1qC4o54ATRGfX_fikWSBe5oA",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU1qa3lOekF3SGhjTk1qWXdNekkyTVRJME56VXdXaGNOTXpZd016SXpNVEkwTnpVdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU1qa3lOekF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRSGRpSVhXTWJ6RXdxazYwanlxQjEwQm5sRUMvOXVJbHlMK1ZwelFaM1MKRGNnbzZBQkxON3pDcFh4anZvZG5wYk9RSUxXRTJNVWZhMGFCZ010amhMZ0VvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVhrU1J6N0N6NXRhMW4vbkc2c1NLCm15Tmo5RVl3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnSWQ2bzdVMG9xTXVoUVcvWHBuNnVubXBlWEVIN3RHZjQKWjVyajBMNWJ1SUlDSVFERk1EMFZ6NHVwMFJYTW1LRy81OE9kWXNPS1Y5bldlbWpoemozeWh6SUlEdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
