apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.mbtux.com
  admin.enabled: "true"
  accounts.admin: apiKey
  kustomize.buildOptions: "--enable-helm"
  # SSO Configuration with Authentik
  dex.config: |
    connectors:
      - type: oidc
        name: Authentik
        config:
          issuer: https://authentik.mbtux.com/application/o/argocd/
          clientID: argocd
          clientSecret: authentik_argo_secret
          redirectURI: https://argocd.mbtux.com/auth/dex/callback
  oidc.config: |
    name: Authentik
    issuer: https://authentik.mbtux.com/application/o/argocd/
    clientID: argocd
    clientSecret: authentik_argo_secret
    redirectURL: https://argocd.mbtux.com/auth/oidc/callback
    scopes: openid email groups profile
    rootURL: https://argocd.mbtux.com
    insecureCA: ""
