apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.mbtux.com
  admin.enabled: "true"
  accounts.admin: apiKey
  kustomize.buildOptions: "--enable-helm"
  oidc.config: |
    name: Authentik
    issuer: https://authentik.mbtux.com/application/o/argocd/
    clientID: ak-outpost-34f6e0b7a65f42079d97a2a916e544c1
    clientSecret: 5OB4WjmXTbVxJyNAa6NeqO2P4HEyXncm5D6jeTwKdII3Qjd5F3ygu7twXY0p
    redirectURL: https://argocd.mbtux.com/auth/oidc/callback
    scopes: openid email groups profile
    rootURL: https://argocd.mbtux.com
    skipVerifyTLS: "true"
