apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - crds/crds.yaml
  - rbac.yaml
  - secret.yaml
  - configmap.yaml
  - redis.yaml
  - repo-server.yaml
  - application-controller.yaml
  - server.yaml
  - projects.yaml
  - applications.yaml
  - cluster-secret.yaml
  - 40-ingress.yaml
