apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  # admin / Mritunjay@123 (base64 encoded)
  admin.password: TXJpdHVuamF5QDEyMw==
  admin.passwordMtime: MjAyNi0wNC0wN1QyMTozMDowMFo=
  # OIDC Client Secret for Authentik (base64 encoded)
  dex.authentik.clientSecret: NU9CNFdqbVhUYlZ4SnlOQWE2TmVxTzJQNEhFeVhuY201RDZqZVR3S2RJSTNRamQ1RjN5Z3U3dHdYWTBw
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:admin
  policy.csv: |
    p, role:org-admin, *, *, *, allow
    g, argocd-admins, role:admin
  scopes: "[groups]"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"
  server.repo.server.strict.tls: "false"
  server.repo.server: "argocd-repo-server:8081"
  controller.repo.server: "argocd-repo-server:8081"
  reposerver.kustomize.buildOptions: "--enable-helm"
  server.enable.static.extensions: "true"
