apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  admin.password: JDJiJDEwJG5wSDVGZHF5VmlIR3BaNk9wSTRpYS5ibWoydmpCcnY2S0syZ2pZeS5xcTZ2VEJ6VXdQN2wu
  admin.passwordMtime: MjAyNi0wMy0yNlQyMDo0MDowMFo=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.mbtux.com
  accounts.admin: apiKey, login
  admin.enabled: "true"
  kustomize.enableHelm: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:admin
  scopes: "[groups]"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"
  server.repo.server.strict.tls: "false"
  server.repo.server: "repo-server:8081"
  controller.repo.server: "repo-server:8081"
