apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  # admin / Mritunjay@123 (base64 encoded)
  admin.password: TXJpdHVuamF5QDEyMwo=
  admin.passwordMtime: "2026-04-07T21:30:00Z"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:admin
  scopes: "[groups]"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/part-of: argocd
data:
  server.insecure: "true"
  server.repo.server.strict.tls: "false"
  server.repo.server: "argocd-repo-server:8081"
  controller.repo.server: "argocd-repo-server:8081"
  reposerver.kustomize.buildOptions: "--enable-helm"
