apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-platform
    app.kubernetes.io/part-of: mbtux-platform
    app.kubernetes.io/component: infrastructure
spec:
  project: mbtux-platform

  source:
    repoURL: https://github.com/mrbhardw-dev/mbtux-kubernetes.git
    targetRevision: main
    path: management-infrastructure/argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
