apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-outpost-token
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-outpost-token
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: authentik-outpost
      property: token
