apiVersion: v1
kind: Secret
metadata:
  name: authentik
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "aE7KPMxyWTWEUtjtrmRtoOiaQQEX3pkL0+kjmPSG+4Z+IVR+sIUJs6ZhwAEBl2lKoEs="
  AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
  AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
  AUTHENTIK_POSTGRESQL__PORT: "5432"
  AUTHENTIK_POSTGRESQL__USER: authentik_user
  AUTHENTIK_POSTGRESQL__PASSWORD: "authentik_pass"
  AUTHENTIK_POSTGRESQL__NAME: authentik_db
  AUTHENTIK_REDIS__HOST: redis
  AUTHENTIK_REDIS__PORT: "6379"
  AUTHENTIK_REDIS__CACHE__HOST: redis
  AUTHENTIK_REDIS__CACHE__PORT: "6379"
