apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik
    creationPolicy: Owner
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: authentik
      property: AUTHENTIK_SECRET_KEY
  - secretKey: AUTHENTIK_ERROR_REPORTING__ENABLED
    remoteRef:
      key: authentik
      property: AUTHENTIK_ERROR_REPORTING__ENABLED
  - secretKey: AUTHENTIK_POSTGRESQL__HOST
    remoteRef:
      key: authentik
      property: AUTHENTIK_POSTGRESQL__HOST
  - secretKey: AUTHENTIK_POSTGRESQL__PORT
    remoteRef:
      key: authentik
      property: AUTHENTIK_POSTGRESQL__PORT
  - secretKey: AUTHENTIK_POSTGRESQL__USER
    remoteRef:
      key: authentik
      property: AUTHENTIK_POSTGRESQL__USER
  - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
    remoteRef:
      key: authentik
      property: AUTHENTIK_POSTGRESQL__PASSWORD
  - secretKey: AUTHENTIK_POSTGRESQL__NAME
    remoteRef:
      key: authentik
      property: AUTHENTIK_POSTGRESQL__NAME
  - secretKey: AUTHENTIK_REDIS__HOST
    remoteRef:
      key: authentik
      property: AUTHENTIK_REDIS__HOST
  - secretKey: AUTHENTIK_REDIS__PORT
    remoteRef:
      key: authentik
      property: AUTHENTIK_REDIS__PORT
  - secretKey: AUTHENTIK_REDIS__CACHE__HOST
    remoteRef:
      key: authentik
      property: AUTHENTIK_REDIS__CACHE__HOST
  - secretKey: AUTHENTIK_REDIS__CACHE__PORT
    remoteRef:
      key: authentik
      property: AUTHENTIK_REDIS__CACHE__PORT
