apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - kubeconfig-secret.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app: headlamp
      multi-cluster: "true"
