apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflared
type: Opaque
stringData:
  TUNNEL_TOKEN: "eyJhIjoiNWZjOGJmOWZkOWQxMDE4MzNlNTUwMTE1ZmRkYWIxMzIiLCJ0IjoiYzZhOGRhMjItYmMzZC00NDYyLTgyMTEtODc1Mzg2NDgwZDlmIiwicyI6Ik0ySTBNV0l3TmpJdE5EY3hPUzAwWVRjMExUazRPRGd0T1RReVpUUXdObUkyTXpVeSJ9"