apiVersion: v1
kind: Secret
metadata:
  name: data-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  server: https://192.168.0.211:6443
  config: |
    {
      "bearerToken": "",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU1qa3dNVGd3SGhjTk1qWXdNekkyTVRJME16TTRXaGNOTXpZd016SXpNVEkwTXpNNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU1qa3dNVGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTV0tPNEtMNGlxTUdUMkxSL3FoZnlBK2xHZGsreHRnYXJJcFBCNnNmc0kKSXNWRmpWeHhSWmp2U2ppTFZyaGZGNFdFd1doNnhCeWhiSUdIczZmSy9iTmpvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUc3bGVKcVF1VEl4NXBDbFA1ZW9MCkxJTUtsQzB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnR3JVRmJnR040TWZWVSt4a29FVU40UlNnRkkxeXEvRTYKZ0pDVU54ekc2V0lDSVFDNllzd00wVThyRmp2MVB3M3lpQnRJM0cwaWZHTDM5ang0TFNBcGtVUkM5QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }