apiVersion: v1
kind: Secret
metadata:
  name: data-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  server: https://192.168.0.211:6443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImVwa2Y5b1h6akotWE1iOV9rXzAxa2hCTDdxcFpMampkdElUUGIwYmFESTAifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoyMDkxODkzNDA4LCJpYXQiOjE3NzY1MzM0MDgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYjcyNzUwYjUtMjNlNS00OTljLTlkOGMtMGM4MzM3MDZiMTAwIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhcmdvY2QtbWFuYWdlciIsInVpZCI6ImFkOTJjMWU2LWI5NTgtNDRlZS1iZDNlLTNlNTdkNjM0NTkxNyJ9fSwibmJmIjoxNzc2NTMzNDA4LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YXJnb2NkLW1hbmFnZXIifQ.VSc_A-u51Lbe3mrIjPFDYWn9wxhGh5OHqI9qhPgMsn42P-2_XNGtQvj-Xn2ItJ3wK89xGKUD07PnI-1q7laVdadS_-rpoPIk6gtFheTJYfRcqokLFEXTsTdNLuTaEG65vQEpmtQSdVerJeSzv_dL-zbKCtmdAQ9G0Loq1GPriG3IkACqKE0N4Vdnu9kVcy3pEBwnautz2Tvij1ZvV5Y7X0lrf0Npu5UgA-6mzi5szRn848EG68h23JrmrhqTZNKOhJhqQG5zSs7mRlWAW00AZlCwfZ9Q16VO8HLwlxETw4tSfQwAMMUN-CMxgsb1x1GiNiiPZJmtyKAFIJTuD1M_9Q",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU1qa3dNVGd3SGhjTk1qWXdNekkyTVRJME16TTRXaGNOTXpZd016SXpNVEkwTXpNNApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU1qa3dNVGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTV0tPNEtMNGlxTUdUMkxSL3FoZnlBK2xHZGsreHRnYXJJcFBCNnNmc0kKSXNWRmpWeHhSWmp2U2ppTFZyaGZGNFdFd1doNnhCeWhiSUdIczZmSy9iTmpvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUc3bGVKcVF1VEl4NXBDbFA1ZW9MCkxJTUtsQzB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnR3JVRmJnR040TWZWVSt4a29FVU40UlNnRkkxeXEvRTYKZ0pDVU54ekc2V0lDSVFDNllzd00wVThyRmp2MVB3M3lpQnRJM0cwaWZHTDM5ang0TFNBcGtVUkM5QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }