apiVersion: v1
kind: Secret
metadata:
  name: mgmt-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  server: https://192.168.0.201:6443
  config: |
    {
      "bearerToken": "",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpRMU1qa3lOekF3SGhjTk1qWXdNekkyTVRJME56VXdXaGNOTXpZd016SXpNVEkwTnpVdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpRMU1qa3lOekF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRSGRpSVhXTWJ6RXdxazYwanlxQjEwQm5sRUMvOXVJbHlMK1ZwelFaM1MKRGNnbzZBQkxON3pDcFh4anZvZG5wYk9RSUxXRTJNVWZhMGFCZ010amhMZ0VvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVhrU1J6N0N6NXRhMW4vbkc2c1NLCm15Tmo5RVl3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnSWQ2bzdVMG9xTXVoUVcvWHBuNnVubXBlWEVIN3RHZjQKWjVyajBMNWJ1SUlDSVFERk1EMFZ6NHVwMFJYTW1LRy81OE9kWXNPS1Y5bldlbWpoemozeWh6SUlEdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }