apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflared-data
type: Opaque
stringData:
  TUNNEL_TOKEN: "eyJhIjoiNWZjOGJmOWZkOWQxMDE4MzNlNTUwMTE1ZmRkYWIxMzIiLCJzIjoiWlRjME1UTmpPREl0WkdNeU1TMDBOREZpTFRoak1USXRORFF5WXpnMU56UTBPREEzIiwidCI6IjQxMzliMTQ5LTk4NzctNDRmNS05Y2NlLTg2N2RiODY4MGIxYiJ9"
